# 客户端个数
n_parties: 1

# 各客户端训练数据集: list
local_train_files:
  - demo_train_a.txt
  - demo_train_b.txt

# 各客户端验证数据集: list
local_dev_files:
  - demo_dev_a.txt
  - demo_dev_b.txt

# 通信轮数：int
n_comm_round: 1

# 每一轮通信前本地模型训练的轮数：int
local_epochs: 1

batch_size: 4

lr: 0.00001

# 验证间隔：int, 每dev_interval个batch验证一次
dev_interval: 1

# 早停轮数：int, 验证指标early_stop_rounds轮未提升时早停
early_stop_rounds: 5

# 初始化种子
init_seed: 0

# 训练类型：str, [supervised, unsupervised]
train_type: supervised

# 模型类型：str, [SimCSE、EntitySimCSE]
model_type: SimCSE

# 地理实体池化层加入层
entity_pooler_insert_layer: 8

# 是否注入地理实体类别
with_entity_type: False